// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkchltjkyrzftrdomvfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrY2hsdGpreXJ6ZnRyZG9tdmZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczMzcxMzUsImV4cCI6MjA1MjkxMzEzNX0.LaW9xiDrnMN8hJ5umLnFHj0Tu0aKJlTQaJFCqTDdwjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);